#!/usr/bin/env bash

# TODO (Run this script as): color magenta && echo hello && color reset

color() {
    echo -ne "\033[$1;$2m"
}

declare -A color_mapping=(
    # REGULAR COLORS
    ['black']=30
    ['red']=31
    ['green']=32
    ['yellow']=33
    ['blue']=34
    ['magenta']=35
    ['cyan']=36
    ['white']=37

    ['bg_black']=40
    ['bg_red']=41
    ['bg_green']=42
    ['bg_yellow']=43
    ['bg_blue']=44
    ['bg_magenta']=45
    ['bg_cyan']=46
    ['bg_white']=47
    # BRIGHT COLORS
    ['bright_black']=90
    ['bright_red']=91
    ['bright_green']=92
    ['bright_yellow']=93
    ['bright_blue']=94
    ['bright_magenta']=95
    ['bright_cyan']=96
    ['bright_white']=97

    ['bg_bright_black']=100
    ['bg_bright_red']=101
    ['bg_bright_green']=102
    ['bg_bright_yellow']=103
    ['bg_bright_blue']=104
    ['bg_bright_magenta']=105
    ['bg_bright_cyan']=106
    ['bg_bright_white']=107
)

if [[ $1 == 'reset' ]]; then
    color 0 00
else
    color 1 ${color_mapping[$1]}
fi
